### ISSUE TITLE
The upgrade menu doesn't shows the upgrades

### ISSUE THREAD

**Issue by creativetnt13** [Derpy-Jacob-903/SallyPokehellHero#2]
![image](https://github.com/Derpy-Jacob-903/SallyPokehellHero/assets/118080784/38da036d-d1a8-4e5d-b0a4-84f065cc82a0)

and on the hero screen it uses an other hero's upgrade description

![image](https://github.com/Derpy-Jacob-903/SallyPokehellHero/assets/118080784/7bf40ad0-37a9-44d2-ac9c-33990064d343)

**Comment by Derpy-Jacob-903** [comment]
@creativetnt13 This has been fixed!
